#! python3

classes = {
    0:  { "class" : "Barbarian",
          "hitDie" : 12,
          "fixedHP" : 7,
          "primaryAbility" : "str",
          "numSkills" : 2,
          "skillChoices" : [1, 3, 7, 10, 11, 17],
          "savingThrows" : ["str", "con"],
        },
    1:  { "class" : "Bard",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "cha",
          "numSkills" : 3,
          "skillChoices" : ['all'],
          "savingThrows" : ["dex", "cha"],
        },
    2:  { "class" : "Cleric",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "wis",
          "numSkills" : 2,
          "skillChoices" : [5, 6, 9, 13, 14],
          "savingThrows" : ["dex", "cha"],
        },
    3:  { "class" : "Druid",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "wis",
          "numSkills" : 2,
          "skillChoices" : [1, 2, 6, 9, 10, 11, 14, 17],
          "savingThrows" : ["int", "wis"],
        },
    4:  { "class" : "Fighter",
          "hitDie" : 10,
          "fixedHP" : 6,
          "primaryAbility" : "str|dex",
          "numSkills" : 2,
          "skillChoices" : [0, 1, 3, 5, 6, 7, 11, 17],
          "savingThrows" : ["str", "con"],
        },
    5:  { "class" : "Monk",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "dex&wis",
          "numSkills" : 2,
          "skillChoices" : [0, 3, 5, 6, 14, 16],
          "savingThrows" : ["str", "dex"],
        },
    6:  { "class" : "Paladin",
          "hitDie" : 10,
          "fixedHP" : 6,
          "primaryAbility" : "str&cha",
          "numSkills" : 2,
          "skillChoices" : [0, 6, 7, 9, 13, 14],
          "savingThrows" : ["wis", "cha"],
        },
    7:  { "class" : "Ranger",
          "hitDie" : 10,
          "fixedHP" : 6,
          "primaryAbility" : "dex&wis",
          "numSkills" : 3,
          "skillChoices" : [1, 3, 6, 8, 10, 11, 16, 17],
          "savingThrows" : ["str", "dex"],
        },
    8:  { "class" : "Rogue",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "dex&int",
          "numSkills" : 4,
          "skillChoices" : [0, 3, 4, 6, 7, 8, 11, 12, 13, 15, 16],
          "savingThrows" : ["dex", "int"],
        },
    9:  { "class" : "Sorcerer",
          "hitDie" : 6,
          "fixedHP" : 4,
          "primaryAbility" : "cha",
          "numSkills" : 2,
          "skillChoices" : [2, 4, 6, 7, 11, 14],
          "savingThrows" : ["con", "cha"],
        },
    10: { "class" : "Warlock",
          "hitDie" : 8,
          "fixedHP" : 5,
          "primaryAbility" : "cha",
          "numSkills" : 2,
          "skillChoices" : [2, 4, 5, 7, 8, 10, 14],
          "savingThrows" : ["wis", "cha"],
        },
    11: { "class" : "Wizard",
          "hitDie" : 6,
          "fixedHP" : 4,
          "primaryAbility" : "int",
          "numSkills" : 2,
          "skillChoices" : [2, 5, 6, 7, 8, 14],
          "savingThrows" : ["int", "wis"],
        },
}

def class_list():
    class_list = []

    for i in range(0, len(classes)):
        class_list.append(classes[i]["class"])

    return class_list
